name: sentralix backend deploy scripts

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: [ self-hosted, Linux, X64, tardis ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Deploy web build to ~/app if present
      run: |
        if [ -d build/web ]; then
          echo "Found build/web. Deploying to ~/app ..."
          mkdir -p "$HOME/app"
          # Копируем содержимое web-сборки в папку приложения на раннере
          cp -R build/web/* "$HOME/app/"
          echo "Deployed build/web contents to $HOME/app"
        else
          echo "build/web not found. Skipping web deploy."
        fi
